[tool.poetry]
name = "prototypes-on-paas"
version = "1.0.0"
description = "Prototypes on Paas"
authors = ["Chris Pettinga <chris.pettinga@digital.trade.gov.uk>"]

[build-system]
requires = ["poetry-core==1.7.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
asgiref = "3.7.2"
beautifulsoup4 = "4.12.2"
black = "23.10.1"
bs4 = "0.0.1"
certifi = "2023.11.17"
cffi = "1.16.0"
charset-normalizer = "3.3.2"
click = "8.1.7"
crossplane = "0.5.8"
cryptography = "41.0.7"
Django = "4.2.8"
django-environ = "0.11.2"
django-extensions = "3.2.3"
gevent = "23.9.1"
greenlet = "3.0.3"
gunicorn = "21.2.0"
idna = "3.6"
MarkupSafe = "2.1.3"
mypy-extensions = "1.0.0"
packaging = "23.2"
pathspec = "0.12.1"
platformdirs = "4.1.0"
pycparser = "2.21"
pyOpenSSL = "23.3.0"
requests = "2.31.0"
sentry-sdk = "1.39.1"
soupsieve = "2.5"
sqlparse = "0.4.4"
tomli = "2.0.1"
typing_extensions = "4.8.0"
urllib3 = "2.1.0"
Werkzeug = "3.0.1"
Zope = "5.9"
django-revproxy = { git = "https://github.com/jazzband/django-revproxy" }
django-log-formatter-ecs = "*"

[tool.poetry.dev-dependencies]
black = "23.12.0"